# baseURL = "https://example.org/"
languageCode = "en-us"
title = "Auto CyberSec Cafe"
theme = "PaperMod"

# 语言设置
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Auto CyberSec Cafe"
    contentDir = "content"
    
    [languages.en.params]
      defaultTheme = "auto"
      ShowShareButtons = true
      ShowToc = true
      ShowReadingTime = true
      ShowBreadCrumbs = true

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 10
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 15
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 30

  [languages.zh]
    languageName = "中文"
    weight = 2
    title = "Auto CyberSec Cafe"
    contentDir = "content"
    
    [languages.zh.params]
      defaultTheme = "auto"
      ShowShareButtons = true
      ShowToc = true
      ShowReadingTime = true
      ShowBreadCrumbs = true

    [languages.zh.menu]
      [[languages.zh.menu.main]]
        identifier = "posts"
        name = "文章"
        url = "/posts/"
        weight = 10
      [[languages.zh.menu.main]]
        identifier = "tags"
        name = "标签"
        url = "/tags/"
        weight = 15
      [[languages.zh.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about/"
        weight = 30
