# baseURL = "https://example.org/"
languageCode = "en-us"
title = "Auto CyberSec Cafe"
theme = "PaperMod"
# Favicon 设置
 assets:
   favicon = "/img/favicon.ico"
   apple_touch_icon = "/img/apple-touch-icon.png"

[params]
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowToc = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  
  # 添加搜索功能配置
  ShowSearchButton = true
  
  # 添加评论功能配置
  comments = true
  
  # Giscus 配置
  [params.giscus]
    repo = "your-github-user/your-repo-name"            # 替换为您的 GitHub 仓库
    repoId = "your-repository-id"                       # 替换为您的仓库 ID
    category = "Announcements"                          # 替换为您想使用的 Discussion 分类
    categoryId = "your-category-id"                     # 替换为分类 ID
    mapping = "pathname"                                # 可选: pathname, url, title, og:title
    reactionsEnabled = "1"                              # 启用反应
    emitMetadata = "0"                                  # 不发送元数据
    inputPosition = "bottom"                            # 评论框位置
    lang = "en"                                         # 语言
    theme = "preferred_color_scheme"                    # 主题跟随系统


[outputs]
  home = ["HTML", "RSS", "JSON"] # 添加 JSON 输出，用于搜索功能

[menu]
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30